version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: books_db_container
    environment:
      POSTGRES_DB: ${DATABASE_URL}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5431:5432"
    restart: always