version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: books_db_container
    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    restart: always